AuctionSystemApp.MVC/Controllers/LoginController.cs
using AuctionSystemApp.Application.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuctionSystemApp.MVC.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly IUserAppService _userAppService;
        public LoginController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Logout()
        {
            Response.Cookies.Append("AuthJwt", "", new CookieOptions
            {
                Expires = DateTimeOffset.UtcNow.AddDays(-1)
            });

            return NoContent();
        }

        [HttpPost]
        public async Task<IActionResult> SendUserOTP([FromForm] string email)
        {
            var result = await _userAppService.SendUserOTP(email);
            return NoContent();
        }

        [HttpPost]
        public async Task<IActionResult> VerifyOtp([FromForm] string email, [FromForm] string otp)
        {
            if (ModelState.IsValid)
            {
                var result = await _userAppService.VerifyUserOTP(email, otp);
                if (result == null)
                    return Unauthorized();
                Console.WriteLine(result);
                Response.Cookies.Append("AuthJwt", result, new CookieOptions
                {
                    HttpOnly = true,
                    Secure = false,
                    SameSite = SameSiteMode.Strict,
                    Expires = DateTime.UtcNow.AddHours(5)
                });

                return Redirect("/Home/Index");
            }
            return Unauthorized();
        }
    }
}

AuctionSystemApp.MVC/Controllers/SignupController.cs
using AuctionSystemApp.Application.DTOs;
using AuctionSystemApp.Application.Interfaces;
using AuctionSystemApp.Domain.Entities;
using AuctionSystemApp.MVC.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuctionSystemApp.MVC.Controllers
{
    [AllowAnonymous]
    public class SignupController : Controller
    {
        private readonly IUserAppService _userAppService;
        public SignupController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _userAppService.CreateNewUser(model.ToDictionary(), model.UserPhoto);
                if (result == null)
                    ModelState.AddModelError(string.Empty, "User creation failed. Please try again.");
                return RedirectToAction("Index", "Home");
            }
            return NoContent();
        }
    }
}

AuctionSystemApp.MVC/Views/Signup/Index.cshtml

<div>
    <h1>Signup</h1>
    <form asp-controller="Signup" asp-action="CreateUser" method="post" enctype="multipart/form-data">

        <div class="signup_input">
            <input type="text" name="Fname" placeholder="Enter Your First Name"/>
        </div>

        <div class="signup_input">
            <input type="text" name="Lname" placeholder="Enter Your Last Name" />
        </div>

        <div class="signup_input">
            <input type="text" name="Email" placeholder="Enter Your Email" />
        </div>

        <div class="signup_input">
            <input type="text" name="Phone" placeholder="Enter Your Phone Number" />
        </div>

        <div class="signup_input">
            <input type="file" name="UserPhoto"/>
        </div>

        <button type="submit">Signup Now!</button>
    </form>
    <p>Already has an account? <a asp-controller="Login" asp-action="Index">Login</a></p>
</div>